# Generated by Django 5.1.1 on 2024-09-17 09:07

import django.db.models.deletion
import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, default=test_app.models.get_default_user_role, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.userrole'),
        ),
    ]
